# Generated by Django 2.1.1 on 2018-09-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180922_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_be_edited', 'Allowed to edit'),)},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author'], 'permissions': (('can_be_edited', 'Allowed to edit'),)},
        ),
    ]
