# Generated by Django 2.1.1 on 2018-09-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180922_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author'], 'permissions': (('can_be_edit', 'Allowed to edit'),)},
        ),
    ]
